# Generated by Django 3.2.11 on 2022-01-27 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'GRC 5F'), (2, 'GRC 4F')], default=None, verbose_name='出勤場所名')),
                ('in_out', models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT')),
                ('time', models.TimeField(verbose_name='打卡時間')),
                ('date', models.DateField(verbose_name='打卡日')),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
